[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' https://wrvuuvzaycvpikbdccbb.supabase.co https://newsapi.org; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https://cdnjs.cloudflare.com https://raw.githubusercontent.com https://*.tile.openstreetmap.org; connect-src 'self' https://wrvuuvzaycvpikbdccbb.supabase.co https://newsapi.org https://*.tile.openstreetmap.org; frame-ancestors 'none';"

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"
  NODE_ENV = "production"

[build.processing]
  skip_processing = false
  minify = true
  css.minify = true
  js.minify = true
  html.minify = true
  images.optimize = true

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"